name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: deps
        run: apt install nlohmann-json-dev libconfig++-dev sqlite3
      - name: make
        run: make
